database:
  host: localhost
  port: 5432
  name: ramschi
  username: postgres
  password: postgres

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${database.host}:${database.port}/${database.name}?schema=ramschi
    username: ${database.username}
    password: ${database.password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    user: ${database.username}
    password: ${database.password}
