database:
  host: localhost
  port: 5432
  name: ramschi
  username: postgres
  password: postgres

server:
  port: 80

image:
  thumbnail:
    height: 70
    max-width: 210
  preview:
    width: 400
    max-height: 1200

spring:
  r2dbc:
    url: r2dbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    properties:
      schema: ramschi
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    user: ${database.username}
    password: ${database.password}
  codec:
    max-in-memory-size: 10MB
logging:
  level:
    ROOT: INFO
